### ISSUE TITLE
dbModel read resource does not implement Zend_Db_Adapter_Abstract

### ISSUE THREAD

**Issue by r-martins** [x86fantini/mahocommerce-docker-starter#1]
After a first setup on Mac, with all default options, when trying to access https://maho.dev:28383/ it loads forever and end up with timeout error.

When doing `docker compose exec php bash` and running `./maho admin:user:list` I got the following error:

> www-data@1301d887f228:~/html$ ./maho admin:user:list
> 
> In Db.php line 171:
>                                                                      
>   dbModel read resource does not implement Zend_Db_Adapter_Abstract  
>                                                                      
> 
> admin:user:list

I'm not sure how much of this is a project error, or Maho error, but I think you'd like to know. :)

Thanks for this project. It seems to be very easy to setup (if works).

**Comment by x86fantini** [comment]
Hello @r-martins and thx for your time spent on my project :)
from what i can see, seems like the Mysql is not started or the DB has not been created. 

can you please share the output from:
```
docker ps
``` 
?

olso can you check from logs that mysql DB has been created?
```
docker compose logs -f
``` 
and
```
docker compose logs db
``` 

you can also checks logs from UI, using https://URL/logz/ (as per documentation here https://github.com/x86fantini/mahocommerce-docker-starter?tab=readme-ov-file#logs-management )

also please check on the created ".env" file that the mysql db, user and pass are there

thank you
S

**Comment by x86fantini** [comment]
Hello @r-martins did you had the time to check my previous answer?

**Comment by x86fantini** [comment]
closing for not following up
